apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: api-boilerplate-hpa
  namespace: {{k8s-ns}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-boilerplate
  minReplicas: {{min-replicas}}
  maxReplicas: {{max-replicas}}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80