apiVersion: v1
kind: Service
metadata:
  name: api-boilerplate
  namespace: {{k8s-ns}}
spec:
  selector:
    app: api-boilerplate
  ports:
    - name: 6001app
      nodePort: 30060
      port: {{port}}
      protocol: TCP
      targetPort: {{port}}
  type: NodePort