apiVersion: v1
kind: Service
metadata:
  name: api-boilerplate-open
  namespace: {{k8s-ns}}
  annotations:
spec:
  ports:
  - name: 6001app
    port: {{port}}
    protocol: TCP
    targetPort: {{port}}
  selector:
    app: api-boilerplate
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: api-boilerplate-private
  namespace: {{k8s-ns}}
  annotations:
    konghq.com/plugins: app-jwt
spec:
  ports:
  - name: 6001app
    port: {{port}}
    protocol: TCP
    targetPort: {{port}}
  selector:
    app: api-boilerplate
  type: ClusterIP